# build environment
FROM node:13.12.0 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm ci --silent

RUN npm install react-scripts -g --silent

COPY . ./

RUN npm run build


# production environment
FROM nginx:1.17.6

COPY --from=build /app/build /usr/share/nginx/html

# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
